# Aspectos Básicos de NumPy Arrays

La manipulación de datos en Python es casi sinónimo de la manipulación de matrices NumPy: incluso las herramientas más nuevas, como Pandas, se crean en torno a la matriz NumPy.
Esta sección presentará varios ejemplos del uso de la manipulación de arreglos NumPy para acceder a datos y subarreglos, y para dividir, remodelar y unir los arreglos.


Cubriremos algunas categorías de manipulaciones básicas de matrices aquí:

- *Attributes of arrays*: Determinación del tamaño, la forma, el consumo de memoria y los tipos de datos de las matrices
- *Indexing of arrays*: Obtener y establecer el valor de elementos de matriz individuales
- *Slicing of arrays*: Obtención y configuración de subarreglos más pequeños dentro de un arreglo más grande
- *Reshaping of arrays*: Cambiando la forma de una matriz dada
- *Joining and splitting of arrays*: Combinar varios arreglos en uno y dividir un arreglo en muchos

## NumPy Array Attributes

Primero analicemos algunos atributos de matriz útiles.
Comenzaremos definiendo tres matrices aleatorias, una matriz unidimensional, bidimensional y tridimensional.
Usaremos el generador de números aleatorios de NumPy, que *sembraremos* con un valor establecido para garantizar que se generen las mismas matrices aleatorias cada vez que se ejecute este código.:

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Cada arreglo tiene los atributos ``ndim`` (La cantidad de dimensiones), ``shape`` (El tamaño de cada dimensión), and ``size`` (El tamaño total de el arreglo):

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Otro atributo muy útil es ``dtype``, El tipo de dato del arreglo:

In [ ]:
print("dtype:", x3.dtype)

dtype: int64


Otros atributos incluido ``itemsize``, el cual lista el tamaño (in bytes) de cada elemento del arreglo, y ``nbytes``, el cual lista el tamaño total (in bytes) del arreglo:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


En general, esperamos que ``nbytes`` sea igual a ``itemsize`` times ``size``.

## Array Indexing: Accediendo a elementos individuales

Si está familiarizado con la indexación de listas estándar de Python, la indexación en NumPy te resultará bastante familiar.

En un arreglo unidimensional, el $i^{th}$ valor (contando desde cero) se puede acceder especificando el índice deseado entre corchetes, al igual que con las listas de Python:

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

5

In [ ]:
x1[4]

7

Para indexar desde el final de la matriz, puede usar índices negativos:

In [ ]:
x1[-1]

9

In [ ]:
x1[-2]

7

En un arreglo multidimensional, se puede acceder a los elementos mediante una tupla de índices separados por comas:

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 0]

3

In [ ]:
x2[2, 0]

1

In [ ]:
x2[2, -1]

7

Los valores también se pueden modificar usando cualquiera de las notaciones de índice anteriores:

In [ ]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Tenga en cuenta que, a diferencia de las listas de Python, las matrices NumPy tienen un tipo fijo.
Esto significa, por ejemplo, que si intentas insertar un valor de coma flotante en una matriz de enteros, el valor se truncará sin avisarte.

In [ ]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accediendo a sub arreglos

Así como podemos usar corchetes para acceder a elementos de arreglos individuales, también podemos usarlos para acceder a subarreglos con la notacion *slice*, marcado por el caracter siguiente (``:``).
La sintaxis de "slice" de NumPy sigue la de la lista estándar de Python; para acceder a una porción de un arreglo ``x``, utiliza esto:
``` python
x[start:stop:step]
```
Si alguno de estos no se especifica, adoptan los valores predeterminados ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
Echaremos un vistazo al acceso a sub-matrices en una dimensión y en múltiples dimensiones.

### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [ ]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

Un caso potencialmente confuso es cuando el valor de ``step`` es negativo.
En este caso, El valor por defaults para ``start`` and ``stop`` Están intercambiadas.
Esto se convierte en una forma conveniente de invertir un array:

In [ ]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Subarreglos Multi-dimensionales 

Los subarreglos multidimensionales funcionan de la misma manera, con varios arreglos separados por comas.
Por ejemplo:

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [ ]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finalmente, las dimensiones del subarreglo pueden incluso invertirse juntas:

In [ ]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Acceder a las filas y columnas de la matriz

Una rutina comúnmente necesaria es acceder a filas o columnas individuales de un array.
Esto se puede hacer combinando la indexación y el "slice", utilizando un segmento vacío marcado con dos puntos. (``:``):

In [ ]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [ ]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


En el caso del acceso a filas, el segmento vacío se puede omitir para una sintaxis más compacta:

In [ ]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as no-copy views

Una cosa importante y extremadamente útil que debe saber acerca de los segmentos de matriz es que devuelven *vistas* en lugar de *copias* de los datos de la matriz.
Esta es un área en la que el "slice" de matrices NumPy difiere del "slice" de listas de Python: en las listas, los "slice" serán copias.
Considere esta matriz bidimensional de antes:

In [ ]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Extraigamos un subarreglo $2 \times 2$ de esto:

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Ahora, si modificamos este subarreglo, ¡veremos que el arreglo original ha cambiado! Observa:

In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [ ]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Este comportamiento predeterminado es bastante útil: significa que cuando trabajamos con grandes conjuntos de datos, podemos acceder y procesar partes de estos conjuntos de datos sin necesidad de copiar el búfer de datos subyacente.

### Creando copias de arrays

A pesar de las buenas características de las vistas de arrays, a veces es útil copiar explícitamente los datos dentro de una matriz o subarreglo. Esto se puede hacer más fácilmente con el métod ``copy()``:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [ ]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

Otro tipo útil de operación es la remodelación de matrices.
La forma más flexible de hacerlo es con el método ``reshape``.
Por ejemplo, si desea colocar los números del 1 al 9 en una cuadrícula de $3 \times 3$, puede hacer lo siguiente:

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Tenga en cuenta que para que esto funcione, el tamaño de la matriz inicial debe coincidir con el tamaño de la matriz reformada.
Siempre que sea posible, el método ``reshape``  utilizará una vista sin copia de la matriz inicial, pero con búferes de memoria no contiguos, este no es siempre el caso.

Otro patrón de reshaping común es la conversión de una matriz unidimensional en una matriz bidimensional de filas o columnas.
Esto se puede lograr con el método ``reshape``, o más fácilmente haciendo uso de la palabra clave ``newaxis`` dentro de el argumento de una operación "slice":

In [ ]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [ ]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Concatenación y división de arreglos

Todas las rutinas anteriores funcionaron en matrices individuales. También es posible combinar varios arreglos en uno y, a la inversa, dividir un solo arreglo en varios arreglos. Echaremos un vistazo a esas operaciones aquí.

### Concatenación de arreglos

La concatenación, o unión de dos arreglos en NumPy, se logra principalmente usando las rutinas ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` tomando una tupla o lista de arreglos como primer argumento, como podemos ver aquí:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

También puede concatenar más de dos arreglos a la vez:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

También se puede utilizar para arreglos bidimensionales.:

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
# concatenate along the first axis
np.concatenate([grid, grid])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

Para trabajar con arreglos de dimensiones mixtas, puede ser más claro usar las funciones ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack):

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

Similarmente, ``np.dstack`` apilará matrices a lo largo del tercer eje.

### División de arreglos

Lo opuesto a la concatenación es la división, que es implementada por las funciones ``np.split``, ``np.hsplit``, and ``np.vsplit``. Para cada uno de estos, podemos pasar una lista de índices que nos dan los puntos de división:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Nota que *N* split-points, Nos lleva a *N + 1* subarreglos.
Las funciones relacionadas ``np.hsplit`` and ``np.vsplit`` son similares:

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarmente, ``np.dsplit`` dividirá arreglos a lo largo del tercer eje.